; Ronin Desktop Application NSIS Installer Script
; This installer is auto-generated by electron-builder

!include "MUI2.nsh"

; Installer Settings
Name "Ronin AI Agent"
OutFile "Ronin-${VERSION}-Setup.exe"
InstallDir "$PROGRAMFILES\Ronin"
RequestExecutionLevel admin

; MUI Settings
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

; Installation Sections
Section "Install"
  SetOutPath "$INSTDIR"
  
  ; Add your files here
  File "*.exe"
  File "*.dll"
  
  ; Create Start Menu Shortcuts
  CreateDirectory "$SMPROGRAMS\Ronin"
  CreateShortcut "$SMPROGRAMS\Ronin\Ronin.lnk" "$INSTDIR\Ronin.exe"
  CreateShortcut "$SMPROGRAMS\Ronin\Uninstall.lnk" "$INSTDIR\uninstall.exe"
  
  ; Create Desktop Shortcut
  CreateShortcut "$DESKTOP\Ronin.lnk" "$INSTDIR\Ronin.exe"
  
  ; Register uninstaller
  WriteUninstaller "$INSTDIR\uninstall.exe"
  
  ; Write to registry for Add/Remove Programs
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Ronin" "DisplayName" "Ronin AI Agent"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Ronin" "UninstallString" "$INSTDIR\uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Ronin" "InstallLocation" "$INSTDIR"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Ronin" "DisplayVersion" "${VERSION}"
SectionEnd

; Uninstall Section
Section "Uninstall"
  RMDir /r "$INSTDIR"
  RMDir /r "$SMPROGRAMS\Ronin"
  Delete "$DESKTOP\Ronin.lnk"
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Ronin"
SectionEnd
